- name: Copiamos el fichero de configuracion interfaces
  template: 
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart red

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
